### ISSUE TITLE
error in preprocess.py

### ISSUE THREAD

**Issue by FNRocha** [DeepMotionEditing/deep-motion-editing#113]
I have downloaded cmu bvh animation from https://sites.google.com/a/cgspeed.com/cgspeed/motion-capture/cmu-bvh-conversion, since it is a CMU animation I chose skeleton type == 4 as instructed in the comments.
Checked the animation in BVH viewer and found no apparent problem.
however, when I followed the instructions to run preprocess for retargetting. I get the following error:

![error](https://user-images.githubusercontent.com/21160476/102002984-b6136f80-3ce0-11eb-87ce-1dcc8798a36b.PNG)

My goal is to use this code to remove some joints. The error message doesn't provide meaningful information so I would like some advice about how to proceed.

**Comment by FNRocha** [comment]
It turns out the names of the joints downloaded in cgspeed are different than the ones in bvh_parser, although I still don't know how to generate the bvh file with the removed joints.

**Comment by PeizhuoLi** [comment]
Hi, regarding the "Problem in file" exception, your understanding is correct. It is triggered because the parser can't find all the joints specified in "course_name" in the given bvh file.

It seems you are trying to save the simplified bvh file by BVH_file.save(). However, this function should have been removed since it was deprecated. So I rewrote it to support your need.

You can clone the newest version and now it should work like this:
```python
file = BVH_file(source_bvh)
file.write(dest_file)
```

**Comment by FNRocha** [comment]
Thank you for answering so quickly, strangely the animation is coming out wrong, I just removed the fingers and the animation is all messy now.
