### ISSUE TITLE
style transfer architecture

### ISSUE THREAD

**Issue by Hellodan-77** [DeepMotionEditing/deep-motion-editing#134]
Did you extract features separately from content movement and style movement in the process of style transfer? Or should the style feature of the latent code of the content be decoded directly through instance normalization (IN), and the style motion is added to the decoded output movement through AdaIN during the decoding process? Which py file is the code part of this part? I don’t understand a little in this part. I would like to trouble you to explain it. Thank you very much!

**Comment by HalfSummer11** [comment]
The content feature is extracted by the content encoder while the style feature is extracted by the style encoder (I guess this is what you mean by "separately"). IN serves as part of the content encoder to strip out style. Basically, there shouldn't be a "style feature" of the content code since it's style-neutral. 
I think the paper or the video would illustrate our method more clearly. The most relevant part in the code is [here](https://github.com/DeepMotionEditing/deep-motion-editing/blob/0efe8831709d15f8a7c58d504b0b4f71d9ee11eb/style_transfer/model.py#L311).

**Comment by Hellodan-77** [comment]
Thank you very much for your reply! My understanding is that you separate the content motions and style motions for feature extraction. For the content motions, the style part is stripped away and the content part is retained, while for the style motions, the style part is retained, and then the content and style processed are combined to get the transferd motions (that is, the output motion)? If so, how do you extract content and style separately for the migration process of style motion as video? (By which I mean, what is the method used? Because I did not understand some things in the article) I hope to receive your reply!

**Comment by HalfSummer11** [comment]
> My understanding is that you separate the content motions and style motions for feature extraction. For the content motions, the style part is stripped away and the content part is retained, while for the style motions, the style part is retained, and then the content and style processed are combined to get the transferred motions (that is, the output motion)?

Yes, exactly. But I am afraid that I still can't get your question. Regarding "separately", since the content and style come from two different input motions, the two motions (no matter in 3D or video) are naturally processed "separately" during encoding. Regarding the "method", as I said, the extraction is done by the content encoder and style encoder, and the detailed architectures can be found in the paper/code.
