### ISSUE TITLE
Full rotation artifacts in retargeted animation 

### ISSUE THREAD

**Issue by rainer7** [DeepMotionEditing/deep-motion-editing#140]
Hi there :)

I trained my own model with motion data we captured at our university.
As you can see in the video, there are artifacts in the result animation, where the skeleton appears to make rotations randomly.
[Grey skeleton = input | orange skeleton = result]

https://user-images.githubusercontent.com/42139568/110971081-b57b8b00-835a-11eb-9fdc-203a9ed69ce0.mp4

1. Do you have an idea what could be the cause of those artifacts?

FYI my dataset contains of 2 groups A and B each containing 2 characters with each 61 animations (244 bvh files in total).

While looking for a reason for those artifacts I noticed that the retargeted skeletons seem a little off their structure (idk if that has anythin to do with it though):

This is the desired target skeleton:
![target skeleton](https://user-images.githubusercontent.com/42139568/110972065-e0b2aa00-835b-11eb-85a7-5d449a4f93ab.png)

And that is the result skeleton:
![Screenshot 2021-03-12 172303](https://user-images.githubusercontent.com/42139568/110972439-4b63e580-835c-11eb-80ab-0bd70ba65a4a.png)

I guess the "virtual" bones' purpose is to connect "free floating" bones. But here something weird happend:
- the Head bone (yellow) shrunk to "zero" (this happend to all end effectors)
- the Chest bone (blue) expands to twice its size not connecting to anything

2. For my project I need the hierarchie of the result skeleton to be the same as the hierarchie of the taget skeleton, is it possible to get rid of the virtual bones after retargeting?

Looking forward to your response and thank you very much for your help! :)

**Comment by PeizhuoLi** [comment]
Hi, thanks for your interest in this project!

Regarding the artifacts, I'm sorry but I haven't seen any similar results through all our development. I can only give you some advice from my instinct:

1. You can try to simply copy root joint rotation from source to target. In some case copy rotation can get some reasonable result.
2. Try to discard GAN_loss by setting parameter --gan_mode=None.
3. It seems to me that you have paired data, i.e. the same motion on all the skeletons. It can greatly training efficiency and performance by using such supervision according to our early experiments. You can use only three losses: reconstruction loss, end-effector loss and a "new" latent-consistency loss. For the "new" latent-consistency loss, simply apply an L2/L1 loss between Enc(motionA_on_character1) and Enc(motionA_on_character2). That will be enough to get a very good model.
4. This can also be an issue with the representation of rotation we used. Quaternion is not a continuous representation for SO(3). Using the 6D representation proposed in [this](https://arxiv.org/abs/1812.07035) paper might help! You can also refer to issue #126.

Also, I'm actually very interested in digging more into this artifacts. If you wouldn't mind, you could email me your dataset and I might be able to find some time to check what's going on. (I'm sorry but I'm really occupied recently so I can't promise it)


Regarding the second question, we used an edge representation in this work (we assume there is a rotation assigned to each bone). You can check issue #46. In an early stage of this project, we used the joint representation and the target skeleton can be the same as the given target. You may implement all the operator on joint as we did. Alternatively, you may also try to calculate the average rotation of all the virtual joint and combine them into one to get the original skeleton.

The "weird" thing you mentioned is because of Blender itself. When render a joint with more than one child, Blender doesn't render it faithfully. Instead, it did some simplification to make the result more "clean" and easy to work with for animators.


Hope this can help! Thanks for your question!

**Comment by rainer7** [comment]
Thanks for your quick reply, I'll try your suggestions and I'll send you an email with the dataset :)
