### ISSUE TITLE
bpy install

### ISSUE THREAD

**Issue by buaaswf** [DeepMotionEditing/deep-motion-editing#146]
Dear @PeizhuoLi ,
I have installed blender2.8, however, when I run 
`blender -P blender_rendering/skinning.py -- --bvh_file [bvh file path] --fbx_file [fbx file path]`
It appears the followings.
`Traceback (most recent call last):
  File "blender_rendering/skinning.py", line 1, in <module>
    import bpy
ModuleNotFoundError: No module named 'bpy'
`
I have prepared the requirements
`Make a symbolic link or simply copy a python interpreter at [blender_path]/2.80/python. E.g. ln -s ~/anaconda3/envs/env_name [blender_path]/2.80/python`

Do you have some suggestions?

**Comment by PeizhuoLi** [comment]
Hi, bpy is a built-in package in Blender. Once you lunch a python script with `blender -P` it should be found automatically. I haven't encountered similar error. I can only suggest you to check your environment (e.g. Blender installation, environment variable). Otherwise you may try to open the script within Blender and run it via Blender's GUI.
