### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by buaaswf** [DeepMotionEditing/deep-motion-editing#149]
Hi @PeizhuoLi 
training style transfer as follows,
`cd style_transfer/data_proc
sh gen_dataset.sh
python style_transfer/train.py`
However, it appears the memory leak.

Have you ever met this?

**Comment by HalfSummer11** [comment]
Hi, could you provide us with more details, e.g. the error messages?
Based on the current information, my suggestion is to check whether `for_try` has been set to `False` in `config.py`. The default option is `True` in order to quickly check whether the code can function well. But it will output images at a very high frequency which may flood your disk space (but not the memory, though).

**Comment by buaaswf** [comment]
I have checked that the code here is the memory leak point.
https://github.com/DeepMotionEditing/deep-motion-editing/blob/0efe8831709d15f8a7c58d504b0b4f71d9ee11eb/style_transfer/train.py#L131

**Comment by HalfSummer11** [comment]
This is where we write latent space visualizations to the TensorBoard, which should work fine if `for_try = False` (with `for_try = True` it will probably write too many images). However, if the problem remains, it's also fine to comment out this line.

**Comment by miaoYuanyuan** [comment]
@buaaswf @HalfSummer11 Hi, when I comment  all the code about get_all_plot. the memory also growing as the train continue.  after some epochs, it will break and output error: out of memory
