### ISSUE TITLE
Remove virutal joints from retargeted skeleton

### ISSUE THREAD

**Issue by rainer7** [DeepMotionEditing/deep-motion-editing#177]
**Anybody that knows how to remove the virtual joints of the retargeted skeleton without corrupting the rotations of the remaining joints?**

Since the Neural Network only works with skeletons, that can be represented as homeomorphic graphs, some skeletons need to be extended by virutal joints, before the Neural Network can process them.
In my case, the original source skeleton (see **green** **skeleton**) is extended by 6 virtual joints (see **blue** **skeleton**). 
<img src="https://user-images.githubusercontent.com/42139568/127934631-16ef2d71-1db0-4527-828c-8f9653b520fe.png" width=40% height=40%> <img src="https://user-images.githubusercontent.com/42139568/127934635-d242e507-d674-4a31-bc2c-5c36ea72f57c.png" width=40% height=40%>

The virtual joints still remain in the retargeted bvh file, but I need it without the virutal joints. My approach of removing them and adjusting the rotations failed, as you can see here (the pose of the **blue skeleton** with virtual joints is **correct** - but after removing the virutal joints the rotations of the skeleton are off (see **green skeleton**)).
<img src="https://user-images.githubusercontent.com/42139568/127934654-a508e935-ebde-4436-8b13-763ae249a442.png" width=25% height=25%><img src="https://user-images.githubusercontent.com/42139568/127934668-d2ef06c4-feb0-48cc-97d0-a9d578152632.png" width=25% height=25%>

The conversion of the t-pose itself is straight forward. But applying the rotations of the virtual joints onto their children does not seem to work for me.

My approach is the following:
1. convert euler angles of bvh-joint to quaternion
2. the rotation of the virtual joint's parent stays the same
3. the rotation of the virtual joint is "skipped" (removed joint from t-pose)
4. the virtual joint's child is multiplied with the virtual joint itself: **q_child = q_virtual  * q_child**

Since my approach didn't work, I tried all kinds of "combinations" - multiplying with the inverse and so on- nothing seems to work. Any ideas?
Thank youu

**Comment by PeizhuoLi** [comment]
Hi, all the virtual joints are introduced because of the edge representation of animation, which is not compatible with bvh file's joint representation. To solve this problem completely from the cause, you'll need to change the code to joint representation and re-train everything.

However, I guess there is a trick that can bypass the whole re-training stuff. Virtual joints are introduced only when a joint has more than one child (let's call that joint p): 

1. Average the rotation of p's child virtual joints, denoted as q_avg.
2. Replace p's rotation by q_avg. (p's original rotation should be zero)
3. Remove p's child virtual joints, connect the child of each virtual joint directly to p. There's no need to touch their rotation.

Since all the q_virtual should be similar, the average step should be easy. As I imagine simply arithmetic average should be fine. Or even randomly pick one instead average could work.

**Comment by rainer7** [comment]
Thanks Peizhou for the quick response!!

I tried your approach with averaging the virtual joints and it works perfectly for the **input.bvh** with the virtual joints **before** it is processed and retargeted by the neural network, as you can see here:
<img src="https://user-images.githubusercontent.com/42139568/128086037-69e032f3-05ad-406b-8096-6168e5e0a448.png" width=30% height=30%>

**However**, when I try the same for the retargeted **result.bvh**, the averaging approach does not work. I think that is due to the fact, that the NN modifies the virtual joints individually so that they are not similar anymore?
<img src="https://user-images.githubusercontent.com/42139568/128086651-5691d064-0fdd-4374-a725-57c4e477c45d.png" width=30% height=30%>

Is there anything else I could try without changing the code to joint representation?
Thank you!

**Comment by PeizhuoLi** [comment]
I thought in the result the rotation for the virtual joints should be similar to input: since it's trained on these data. Could you check if p's children's rotations are similar? If it's similar you may still you the approach, but remember also add p's rotation. 

If it's not true (it could happen since the network might learn to use the "flexibility" it for further adjustment), another alternative can be use IK. You can use one of the approaches above as the initialization for the joint rotation. Then use the joint location of output (the skeleton with virtual joints) as constrain (similar to [this](https://github.com/DeepMotionEditing/deep-motion-editing/blob/19604abdc0ead66f8c82d9211b8c5862c6a68089/retargeting/models/IK.py#L135) one) to optimize the joint rotations.

**Comment by rainer7** [comment]
Hi Peizhou, thanks for the quick reply! 
I actually just noticed why your approach didn't work with the result BVH: my BVH parser only works with the rotation order XYZ. The rotation channels of the input BVH are XYZ, whereas the result BVH is ZYX. A stupid mistake, my bad! 
I adjusted the parser and now your first approach works well - it's still not the exact same as with virtual joints, but it is really close and it will do! Maybe adding p's rotation to q_avg could help too, I will try that!
Thank you and sorry again for my silly mistake - I hope I didn't waste your time!
