### ISSUE TITLE
In retarget ,  how can we get mean & var .npy  ?

### ISSUE THREAD

**Issue by xinzi2018** [DeepMotionEditing/deep-motion-editing#37]

**Comment by PeizhuoLi** [comment]
We are planning to release related details in 1~2 weeks. More details in #31. Thank you!

**Comment by xinzi2018** [comment]
thanks a lot !

**Comment by crissallan** [comment]
If you print out the shape of mean or var, you will find that the shape of them are like[(simple_joints_number-1)*4+3, 1], because they're calculated by using the rotation of all edges("edges" means all simplified skeleton joints without the ROOT joint) and the ROOT joint's position w.r.t all bvh files' frames.
So, a possible way to calculate the mean & var by yourself, is to read the edges' rotation and root position of every frame of every bvh file, then calculate the mean and var, then reshape into a numpy array with shape:[(simple_joints_number-1)*4+3, 1]

**Comment by PeizhuoLi** [comment]
You can get mean and var use retargeting/datasets/preprocess.py. For more details please refer to dataset section in instructions for training from scratch.
