### ISSUE TITLE
Question about Mixamo dataset

### ISSUE THREAD

**Issue by GIMPS** [DeepMotionEditing/deep-motion-editing#53]
Hi, great works! I am curious about the dataset setting: are all of Mixamo animations manually designed or are they also created by some kind of _motion retargeting_? It raises my doubts when some characters in Mixamo, e.g., Sword Woman, do not behave naturally in certain motions. If the Mixamo animations are not designed by human artists, then why can we take them as ground truth (please feel free to correct me)? Thanks.

**Comment by crissallan** [comment]
> Hi, great works! I am curious about the dataset setting: are all of Mixamo animations manually designed or are they also created by some kind of _motion retargeting_? It raises my doubts when some characters in Mixamo, e.g., Sword Woman, do not behave naturally in certain motions. If the Mixamo animations are not designed by human artists, then why can we take them as ground truth (please feel free to correct me)? Thanks.

I have the same questions as you! I found that there existing model intersections for some motions of a few characters like "Mousey"

**Comment by bmahlbrand** [comment]
ground truth is whatever you decide it is, no?

**Comment by crissallan** [comment]
> ground truth is whatever you decide it is, no?

Yes, but what I concerned about is that: if the motion data of different characters are not created manually but in an automatic motion retargeting methods, then what our deep learning models learns is nothing more than this "automatic retargting method".  Then the motivation of using deep learning methodology is worth to thinking about.

But, I still think this project is worth to exploring!

**Comment by GIMPS** [comment]
@bmahlbrand Ground truth upper bounds a learning-based method's performance. @crissallan Good to hear a similar concern! And surely, this is an interesting project. I am just not quite sure about how Mixamo animations are created and why they can be taken as supervision signals. @PeizhuoLi @kfiraberman  Please kindly have a look! Thank you in advance.

**Comment by kfiraberman** [comment]
Great question. As far as I know, motion retargeting procedure within Mixamo is automatic for the "intra-structural" examples (same skeletal structure). However, since there is no existing fully-automated way to perform cross-structural retargeting, 
 at least one "cross-structural" example from each motion should be generated manually (or semi-manually; IK + manual corrections for the missing correspondences), then this example can be retargeted to the other skeletons with a similar structure. 
 
I agree with the claim that training on examples that were automatically generated is equivalent to train a network to approximate an existing retargeting algorithm which sounds useless in some aspects (but maybe some benefits can be gained, like better processing times). However, since there is no existing "cross-structural" retargeting algorithm, in our case the network learns a new "algorithm".

In addition, remember that the framework is general. It was trained on Mixamo only for evaluation purposes - there was no better (publicly available) way to quantitatively evaluate the performance.

**Comment by bmahlbrand** [comment]
> In addition, remember that the framework is general. It was trained on Mixamo only for evaluation purposes - there was no better (publicly available) way to quantitatively evaluate the performance.

To be clear, this is what I was driving at. Not that it will somehow result in a realistic manifold by training on unnatural motion.

**Comment by GIMPS** [comment]
Thank you so much for your reply @kfiraberman, that clearly clarifies my concern!
