### ISSUE TITLE
Is it possible to use my own mocap dataset or videopose3d estimation result for training

### ISSUE THREAD

**Issue by zitongzhan** [DeepMotionEditing/deep-motion-editing#75]
Hello,

As I glance through the code, I guess the function for converting my own mocap dataset or videopose3d estimation result to `.bvh` file is not provided. Typical mocap or pose estimation result only contains the xyz coordinate of each joint, but rotations are not provided. Do you have any suggestions for me to achieve this goal? Like, using pose estimation skeletons in retargeting. I see someone have mentioned this before in [this post](https://github.com/DeepMotionEditing/deep-motion-editing/issues/34#issuecomment-648003912). Thanks in advance!

**Comment by kfiraberman** [comment]
Converting 3D positions (output of typical pose estimation methods) to rotations is an ill-posed problem. 
Usually, people use Inverse Kinematics (IK) to perform such a step. The IK provided [here](utils/InverseKinematics.py) can be used as a baseline for such an implementation, but note that there is no such use case in our code since we only use it to correct foot contact positions. I believe that the results you want to achieve (3D positions -> 3D rotations) are depended on the quality of the 3D positions you have.
